name: Build JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean package --batch-mode

      - name: Archive JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: shopping-cart-jar
          path: target/shopping-cart.jar
